import { Card as ICard } from '@/types/Card';
import { Metadata } from 'next';
import { useState } from 'react';
import CreateCardForm from './components/CreateCardForm';
import { API } from '../../env.config';
import Card from './components/Card';
// import {getUserSession}


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const getCards = async () => {


  const response = await fetch(`${API}/cards`, { cache: 'no-store' })

  if (!response.ok) {
    throw new Error('Failed to fetch cards')
  }

  return response.json()
}

export default async function Home() {

  // const [input, setInput] = useState()

  let cards: ICard[] = await getCards()

  console.log(cards)

  return (
    <main>
      <CreateCardForm />

      <div className='flex flex-wrap justify-center  gap-5'>
        {cards.map(card => (
          // <div className='p-3' key={String(card.id)}>{card.name}</div>
          <Card key={String(card.id)} card={card} />
        ))}
      </div>
    </main>
  );
}
