import { Card } from '@/types/Card';
import { Metadata } from 'next';
import { useState } from 'react';
import CreateCardForm from './components/CreateCardForm';
import { API } from '../../env.config';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const getCards = async () => {
  const response = await fetch(`${API}/cards`, { cache: 'no-store' })

  if(!response.ok){
    throw new Error('Failed to fetch cards')
  }

  return response.json()
} 

export default async function Home() {

  // const [input, setInput] = useState()

  let cards: Card[] = await getCards()

  return (
    <main>
      <CreateCardForm />
      {cards.map(card => (
        <div className='p-3' key={String(card.id)}>{card.name}</div>
      ))}
    </main>
  );
}
