import { Card } from '@/types/Card';
import axios from 'axios'
import { Metadata } from 'next';
import { useState } from 'react';
import CreateCardForm from './components/CreateCardForm';
import { API } from '../../env.config';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Home() {

  // const [input, setInput] = useState()

  let cards: Card[] = [];

  try {
    const response = await axios.get(`${API}/cards`);
    console.log(response.data)
    cards = response.data;
  } catch (error) {
    console.error('Error fetching users:', error);
  }

  return (
    <main>
      <CreateCardForm />
      {cards.map(card => (
        <div className='p-3' key={String(card.id)}>{card.name}</div>
      ))}
    </main>
  );
}
